"""Add user tier column for free/premium subscription model

Revision ID: 0b644f58a79c
Revises: b008a01c9da3
Create Date: 2025-09-21 16:29:43.871108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b644f58a79c'
down_revision: Union[str, Sequence[str], None] = 'b008a01c9da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    op.execute("CREATE TYPE usertier AS ENUM ('FREE', 'PREMIUM')")
    op.add_column('users', sa.Column('tier', sa.Enum('FREE', 'PREMIUM', name='usertier'), nullable=False, server_default='FREE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tier')
    op.execute("DROP TYPE usertier")
    # ### end Alembic commands ###
