"""Add admin user role

Revision ID: b008a01c9da3
Revises: 61756325e6a8
Create Date: 2025-09-21 14:40:54.454232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b008a01c9da3'
down_revision: Union[str, Sequence[str], None] = '61756325e6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False))
    op.add_column('users', sa.Column('created_via_receipt', sa.Boolean(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'created_via_receipt')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
