name: deploy-functions-dev
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip wheel
          pip install -r requirements.txt
          rm -rf build && mkdir -p build
          pip install -r requirements.txt -t build/
          cp -R * build/
          cd build && zip -r ../app.zip . && cd ..
      - uses: azure/functions-action@v1
        with:
          app-name: fa-axlypro-dev
          package: app.zip
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_DEV }}
